using System;
using System.Collections.Generic;
using BLL.BusinessExceptions;
using BLL.Interfaces;
using DataAccessLayer.DBAccesses;
using DTO;
using Microsoft.Extensions.Configuration;

namespace BLL.Managers
{
    /// <summary>
    /// Manager to create, get, change and delete orders
    /// </summary>
    public class OrderManager : IOrderManager
    {
        private OrdersDB OrdersDb { get; }
        private CouriersDB CouriersDb { get; }
        private CompositionDB CompositionDb { get; }
        private DishesDB DishesDb { get; }
        private IConfiguration Configuration { get; }
        private Utilities Utilities { get; }

        /// <summary>
        /// Manager constructor
        /// </summary>
        /// <param name="configuration">The configuration used to inject the manager</param>
        public OrderManager(IConfiguration configuration)
        {
            Configuration = configuration;
            Utilities = new Utilities(Configuration);
            OrdersDb = new OrdersDB(Configuration);
            CouriersDb = new CouriersDB(Configuration);
            CompositionDb = new CompositionDB(Configuration);
            DishesDb = new DishesDB(Configuration);
        }

        /// <summary>
        /// Method to create a new order
        /// </summary>
        /// <param name="idCustomer">The primary key of the customer who place the order</param>
        /// <param name="idArea">The primary key of the area the customer is delivered</param>
        /// <param name="expectedDeliveryTime">The expected delivery time</param>
        /// <param name="deliveryAddress">The delivery address</param>
        /// <returns>Returns the primary key of the newly created order</returns>
        public int CreateNewOrder(int idCustomer, int idArea, DateTime expectedDeliveryTime, string deliveryAddress)
        {

            // Finds an available courier in the area
            int idCourier = -1;
            List<Courier> availableCouriers = CouriersDb.GetAllCouriersByArea(idArea);

            //no courier found at this area
            if (availableCouriers == null)
            {
                throw new BusinessRuleException("No courier registered at area " + idArea);
            }

            //checking if the courier have less than 5 orders per 30 minutes interval
            //stops looping through couriers when one is found
            foreach (var c in availableCouriers)
            {

                //orders are ordered from the latest to the earliest expectedDeliveryTime
                List<Order> currentOrders = GetAllOrdersByCourier(c.IdCourier);

                int nbOrdersIn30Minutes = 0;

                //if the courier has no delivery, no need to check further
                if (currentOrders == null)
                {
                    idCourier = c.IdCourier;
                    break;
                }

                //checking if the courier has less than 5 orders per 30 minutes interval
                foreach (var o in currentOrders)
                {

                    //dateTime.minValue is the default dateTime value
                    //so if it is minValue, then the order has not been delivered
                    if (o.TimeOfDelivery != DateTime.MinValue) continue;


                    if (expectedDeliveryTime <= o.ExpectedDeliveryTime)
                    {
                        //checking for the orders later than the one in creation
                        if (expectedDeliveryTime.AddMinutes(15) >= o.ExpectedDeliveryTime)
                        {
                            nbOrdersIn30Minutes++;
                        }
                    }
                    else
                    {
                        //checking for the orders earlier than the one in creation
                        if (o.ExpectedDeliveryTime.AddMinutes(15) >= expectedDeliveryTime)
                        {
                            nbOrdersIn30Minutes++;
                        }
                        else
                        {
                            //orders are ordered from the latest to the earliest expectedDeliveryTime, so past this point, orders
                            //are more than 15 minutes earlier from the current order
                            break;
                        }
                    }
                }

                if (nbOrdersIn30Minutes < Utilities.MaxOrdersSimultaneously)
                {
                    idCourier = c.IdCourier;
                    break;
                }
            }

            // if no courier were found, throw businessRuleException
            if (idCourier == -1)
            {
                throw new BusinessRuleException("No courier available at area: " + idArea);
            }

            //addOrder return the order's id generated by sql server
            int idOrder = OrdersDb.AddOrder(idCustomer, idCourier, idArea, expectedDeliveryTime, deliveryAddress);
            if (idOrder == -1)
            {
                throw new DataBaseException("Error occurred, order was not created.");
            }
            return idOrder;
        }

        /// <summary>
        /// Method to delete an order. 
        /// </summary>
        /// <param name="idOrder">The primary key of the order to be deleted</param>
        public void DeleteOrder(int idOrder)
        {
            Order order = OrdersDb.GetOrderById(idOrder);

            //default value for dateTime is minValue
            //so if it is minValue, then order has already been delivered
            if (order.TimeOfDelivery != DateTime.MinValue)
            {
                throw new BusinessRuleException("Cannot delete an order who already has been delivered");
            }

            DateTime deliveryTime = order.ExpectedDeliveryTime;
            if (DateTime.Now.AddHours(3) > deliveryTime)
            {
                throw new BusinessRuleException("Orders have to be cancelled at least 3 hours before");
            }

            //compositions related to the order must be deleted first to respect referential integrity 
            CompositionDb.DeleteCompositionsByOrder(idOrder);
            OrdersDb.DeleteOrder(idOrder);
        }

        /// <summary>
        /// Method to set the order to delivered/undelivered
        /// </summary>
        /// <param name="idOrder">The primary key of the affected order</param>
        public void SetOrderToDelivered(int idOrder)
        {

            /*
             * invert the current order's state
             * if the order has already been set to delivered, sets it to not delivered
             * if the order hasn't been delivered, sets it to delivered
             */

            if (GetOrderById(idOrder).TimeOfDelivery != DateTime.MinValue)
            {
                //result is the number of rows affected, so if it is 0 then the status was not updated
                int resultUnDelivered = OrdersDb.SetOrderToUnDelivered(idOrder);
                if (resultUnDelivered == 0)
                {
                    throw new DataBaseException("Error occurred, delivery time of order " + idOrder + " has not been set.");
                }
                return;
            }

            //result is the number of rows affected, so if it is 0 then the status was not updated
            int result = OrdersDb.SetOrderToDelivered(idOrder);
            if (result == 0)
            {
                throw new DataBaseException("Error occurred, delivery time of order " + idOrder + " has not been set.");
            }

        }

        /// <summary>
        /// Method to get all orders from a customer
        /// </summary>
        /// <param name="idCustomer">The primary key of the customer</param>
        /// <returns>Returns a list of Order objects</returns>
        public List<Order> GetAllOrdersByCustomer(int idCustomer)
        {
            return OrdersDb.GetAllOrdersByCustomer(idCustomer);
        }

        /// <summary>
        /// Method to get all orders delivered by a courier
        /// </summary>
        /// <param name="idCourier">The primary key of the courier</param>
        /// <returns>Returns a list of Order objects</returns>
        public List<Order> GetAllOrdersByCourier(int idCourier)
        {
            return OrdersDb.GetAllOrdersByCourier(idCourier);
        }

        /// <summary>
        /// Method to get all orders from a restaurant
        /// </summary>
        /// <param name="idRestaurant">The primary key of the restaurant</param>
        /// <returns>Returns a list of Order objects</returns>
        public List<Order> GetAllOrdersByRestaurant(int idRestaurant)
        {
            return OrdersDb.GetAllOrdersByRestaurant(idRestaurant);
        }

        /// <summary>
        /// Method to set the total to an order according to its compositions
        /// </summary>
        /// <param name="idOrder">The primary key of the affected order</param>
        public void SetTotal(int idOrder)
        {
            List<Composition> compositions = CompositionDb.GetCompositionsByOrder(idOrder);

            int total = 0;
            foreach (var c in compositions)
            {
                Dish dish = DishesDb.GetDishById(c.ID_Dish);
                total += dish.Price * c.Quantity;
            }
            OrdersDb.SetTotal(idOrder, total);
        }

        /// <summary>
        /// Method to get an order by its id
        /// </summary>
        /// <param name="idOrder">The primary key of the order</param>
        /// <returns>Returns an Order object</returns>
        public Order GetOrderById(int idOrder)
        {
            return OrdersDb.GetOrderById(idOrder);
        }
    }
}
